# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main Updated

on:
  push:
    branches: [main]

jobs:
  pr:
    uses: ./.github/workflows/pr.yml
    secrets: inherit

  # Second Job
  build-eas:
    needs: pr
    uses: ./.github/workflows/build-eas.yml
    secrets: inherit